-- Add 'OWNER_PLUS' to 'OwnerPlan' enum
ALTER TYPE "OwnerPlan" ADD VALUE IF NOT EXISTS 'OWNER_PLUS';

-- Add 'OWNER_PLUS', 'SINGLE_LISTING', and 'SINGLE_OFFER' to 'PaymentType' enum
ALTER TYPE "PaymentType" ADD VALUE IF NOT EXISTS 'OWNER_PLUS';
ALTER TYPE "PaymentType" ADD VALUE IF NOT EXISTS 'SINGLE_LISTING';
ALTER TYPE "PaymentType" ADD VALUE IF NOT EXISTS 'SINGLE_OFFER';
