ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'EKYC_RESUBMISSION_REQUIRED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PROPERTY_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'REVIEW_REJECTED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TENANT_REQUEST_APPROVED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'TENANT_REQUEST_REJECTED';
