-- Intentionally empty.
--
-- `20260728120000_owner_plus_tenant_offers_attachments_admin_role` is the
-- canonical migration for these schema changes. This historical placeholder
-- remains so already-ordered migration histories stay contiguous, but it must
-- not repeat enum, column, table, index, or foreign-key creation during
-- `prisma migrate deploy` on a clean database.
