"""Persistent Chroma vector-storage API for PropMatch.

Embeddings are generated by Cohere in the NestJS backend.  This service only
stores, queries, and deletes the supplied vectors, keeping the production image
free of sentence-transformers, PyTorch, and model files.
"""

from __future__ import annotations

import logging
import os
from functools import lru_cache
from pathlib import Path
from typing import Any

import chromadb
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel, Field

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("propmatch.chroma")

CHROMA_PATH = Path(os.getenv("CHROMA_PATH", "./chroma_data"))
COLLECTION_NAME = os.getenv(
    "CHROMA_COLLECTION", "propmatch_properties_cohere_v1"
)

app = FastAPI(title="PropMatch Chroma Store")


class UpsertRequest(BaseModel):
    collection: str = Field(default=COLLECTION_NAME, min_length=1)
    id: str
    document: str = Field(min_length=1)
    embedding: list[float] = Field(min_length=1)
    metadata: dict[str, str | int | float | bool]


class QueryRequest(BaseModel):
    collection: str = Field(default=COLLECTION_NAME, min_length=1)
    embedding: list[float] = Field(min_length=1)
    n_results: int = Field(default=10, ge=1, le=100)


class DeleteRequest(BaseModel):
    collection: str = Field(default=COLLECTION_NAME, min_length=1)
    id: str = Field(min_length=1)


@lru_cache(maxsize=4)
def get_collection(collection_name: str = COLLECTION_NAME) -> Any:
    CHROMA_PATH.mkdir(parents=True, exist_ok=True)
    client = chromadb.PersistentClient(path=str(CHROMA_PATH))
    return client.get_or_create_collection(
        name=collection_name,
        metadata={"hnsw:space": "cosine"},
        embedding_function=None,
    )


@app.get("/health")
def health() -> dict[str, str]:
    # Touch the persistent collection so Docker only marks the service healthy
    # after Chroma can open the mounted data directory.
    get_collection()
    return {"status": "ok", "collection": COLLECTION_NAME}


@app.post("/upsert")
def upsert(request: UpsertRequest) -> dict[str, str]:
    try:
        get_collection(request.collection).upsert(
            ids=[request.id],
            documents=[request.document],
            embeddings=[request.embedding],
            metadatas=[request.metadata],
        )
        return {"status": "upserted", "collection": request.collection}
    except Exception as error:  # pragma: no cover - Chroma failures
        logger.exception("Chroma upsert failed")
        raise HTTPException(status_code=503, detail="Chroma upsert failed") from error


@app.post("/query")
def query(request: QueryRequest) -> dict[str, Any]:
    try:
        return get_collection(request.collection).query(
            query_embeddings=[request.embedding],
            n_results=request.n_results,
            include=["documents", "metadatas", "distances"],
        )
    except Exception as error:  # pragma: no cover - Chroma failures
        logger.exception("Chroma query failed")
        raise HTTPException(status_code=503, detail="Chroma query failed") from error


@app.post("/delete")
def delete(request: DeleteRequest) -> dict[str, str]:
    try:
        get_collection(request.collection).delete(ids=[request.id])
        return {"status": "deleted", "collection": request.collection}
    except Exception as error:  # pragma: no cover - Chroma failures
        logger.exception("Chroma delete failed")
        raise HTTPException(status_code=503, detail="Chroma delete failed") from error
